services:
  ticket:
    create-ticket:
      scheme: ${CREATE_TICKET_SCHEME}
      host: ${CREATE_TICKET_HOST}
      port: ${CREATE_TICKET_PORT}
      uri: ${CREATE_TICKET_URI}

logging:
  level:
    root: INFO
