services.ticket.create-ticket.scheme=${CREATE_TICKET_SCHEME}
services.ticket.create-ticket.host=${CREATE_TICKET_HOST}
services.ticket.create-ticket.port=${CREATE_TICKET_PORT}
services.ticket.create-ticket.uri=${CREATE_TICKET_URI:/api/case/v1/ticket}
#services.ticket.create-ticket.uri=/api/case/v1/ticket

logging.level.root=INFO
